# Generated by Django 3.1.3 on 2020-12-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('content', models.TextField(blank=True, max_length=50, null=True, verbose_name='Descripción ')),
            ],
        ),
    ]
