# Generated by Django 3.1.3 on 2020-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201201_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='content',
            field=models.TextField(max_length=50, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
